repos:
  - repo: https://github.com/kamadorueda/alejandra
    rev: 4.0.0
    hooks:
      - id: alejandra-system
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: https://github.com/editorconfig-checker/editorconfig-checker
    rev: v3.2.1
    hooks:
      - id: editorconfig-checker
